[package]
name = "pythonbuild"
version = "0.1.0"
authors = ["Gregory Szorc <gregory.szorc@gmail.com>"]
edition = "2018"

[dependencies]
anyhow = "1"
bytes = "1.1"
clap = "3"
duct = "0"
flate2 = "1"
futures = "0"
goblin = "0"
hex = "0"
octocrab = { version = "0", features = ["rustls"] }
once_cell = "1"
rayon = "1"
reqwest = {version = "0", features = ["rustls"] }
scroll = "0"
semver = "1"
serde_json = "1"
serde = { version = "1", features = ["derive"] }
sha2 = "0"
tar = "0"
tempfile = "3"
tokio = "1"
version-compare = "0"
zip = "0"
zstd = "0"

[dependencies.tugger-binary-analysis]
version = "0.4.0-pre"
git = "https://github.com/indygreg/PyOxidizer.git"
rev = "15b9f3913acf9e0f460cebbeb039f1d57c9d291d"
