on:
  push:
  pull_request:
  schedule:
    - cron: '13 11 * * *'
jobs:
  # We need to build our own sccache until e6326bc8a20ee06af37e16a3a7a14e3374c66c66
  # is in a released version.
  sccache:
    runs-on: 'macos-11'
    steps:
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true
          profile: minimal

      - uses: actions/checkout@v2
        with:
          repository: mozilla/sccache
          # Update cache key if this changes.
          ref: e6326bc8a20ee06af37e16a3a7a14e3374c66c66
          fetch-depth: 0

      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-sccache-${{ hashFiles('Cargo.lock') }}-0

      - name: Build sccache
        run: |
          cargo build --release

      - name: Upload sccache executable
        uses: actions/upload-artifact@v2
        with:
          name: sccache
          path: target/release/sccache

  pythonbuild:
    runs-on: 'macos-11'
    steps:
      - uses: actions/checkout@v2

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true
          profile: minimal

      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-pythonbuild-${{ hashFiles('Cargo.lock') }}

      - name: Build
        run: |
          cargo build --release

      - name: Upload pythonbuild Executable
        uses: actions/upload-artifact@v2
        with:
          name: pythonbuild
          path: target/release/pythonbuild

  toolchain:
    needs:
      - sccache
    runs-on: 'macos-11'
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      SCCACHE_BUCKET: 'python-build-standalone-sccache'
      SCCACHE_S3_USE_SSL: '1'
      SCCACHE_IDLE_TIMEOUT: '0'
    steps:
      - uses: actions/checkout@v2

      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Download sccache
        uses: actions/download-artifact@v2
        with:
          name: sccache

      - name: Start sccache
        run: |
          chmod +x sccache
          ./sccache --start-server

      - name: Build
        run: |
          python3.9 ./build-macos.py --make-target toolchain

      - name: Stop sccache
        run: |
          ./sccache -s

      - name: Upload Toolchain Archive
        uses: actions/upload-artifact@v2
        with:
          name: toolchain
          path: build/clang-*.tar

  build:
    strategy:
      fail-fast: false
      matrix:
        build:
          # macOS on Apple hardware. Can't do PGO because GitHub Apple hardware
          # is Intel.
          - target_triple: 'aarch64-apple-darwin'
            py: 'cpython-3.8'
            optimizations: 'debug'
          - target_triple: 'aarch64-apple-darwin'
            py: 'cpython-3.8'
            optimizations: 'noopt'
          - target_triple: 'aarch64-apple-darwin'
            py: 'cpython-3.8'
            optimizations: 'lto'

          - target_triple: 'aarch64-apple-darwin'
            py: 'cpython-3.9'
            optimizations: 'debug'
          - target_triple: 'aarch64-apple-darwin'
            py: 'cpython-3.9'
            optimizations: 'noopt'
          - target_triple: 'aarch64-apple-darwin'
            py: 'cpython-3.9'
            optimizations: 'lto'

          - target_triple: 'aarch64-apple-darwin'
            py: 'cpython-3.10'
            optimizations: 'debug'
          - target_triple: 'aarch64-apple-darwin'
            py: 'cpython-3.10'
            optimizations: 'noopt'
          - target_triple: 'aarch64-apple-darwin'
            py: 'cpython-3.10'
            optimizations: 'lto'

          # macOS on Intel hardware. This is pretty straightforward. We exclude
          # noopt because it doesn't provide any compelling advantages over PGO
          # or LTO builds.
          - target_triple: 'x86_64-apple-darwin'
            py: 'cpython-3.8'
            optimizations: 'debug'
          - target_triple: 'x86_64-apple-darwin'
            py: 'cpython-3.8'
            optimizations: 'lto'
          - target_triple: 'x86_64-apple-darwin'
            py: 'cpython-3.8'
            optimizations: 'pgo'
          - target_triple: 'x86_64-apple-darwin'
            py: 'cpython-3.8'
            optimizations: 'pgo+lto'

          - target_triple: 'x86_64-apple-darwin'
            py: 'cpython-3.9'
            optimizations: 'debug'
          - target_triple: 'x86_64-apple-darwin'
            py: 'cpython-3.9'
            optimizations: 'lto'
          - target_triple: 'x86_64-apple-darwin'
            py: 'cpython-3.9'
            optimizations: 'pgo'
          - target_triple: 'x86_64-apple-darwin'
            py: 'cpython-3.9'
            optimizations: 'pgo+lto'

          - target_triple: 'x86_64-apple-darwin'
            py: 'cpython-3.10'
            optimizations: 'debug'
          - target_triple: 'x86_64-apple-darwin'
            py: 'cpython-3.10'
            optimizations: 'lto'
          - target_triple: 'x86_64-apple-darwin'
            py: 'cpython-3.10'
            optimizations: 'pgo'
          - target_triple: 'x86_64-apple-darwin'
            py: 'cpython-3.10'
            optimizations: 'pgo+lto'

          # iOS targeting mobile hardware. Can't do PGO during cross-compiles.
          # Can't cross-compile until Python 3.9.
          - target_triple: 'aarch64-apple-ios'
            py: 'cpython-3.9'
            optimizations: 'debug'
          - target_triple: 'aarch64-apple-ios'
            py: 'cpython-3.9'
            optimizations: 'noopt'
          - target_triple: 'aarch64-apple-ios'
            py: 'cpython-3.9'
            optimizations: 'lto'

          # iOS targeting simulator. Can't do PGO during cross-compiles.
          # Can't cross-compile until Python 3.9.
          - target_triple: 'x86_64-apple-ios'
            py: 'cpython-3.9'
            optimizations: 'debug'
          - target_triple: 'x86_64-apple-ios'
            py: 'cpython-3.9'
            optimizations: 'noopt'
          - target_triple: 'x86_64-apple-ios'
            py: 'cpython-3.9'
            optimizations: 'lto'
    needs:
      - pythonbuild
      - toolchain
    runs-on: 'macos-11'
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Download pythonbuild
        uses: actions/download-artifact@v2
        with:
          name: pythonbuild
          path: build

      - name: Download toolchain
        uses: actions/download-artifact@v2
        with:
          name: toolchain
          path: build

      - name: Build
        run: |
          export APPLE_HOST_SDK_PATH=/Applications/Xcode_12.5.1.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.3.sdk

          if [ "${{ matrix.build.target_triple }}" = "aarch64-apple-darwin" ]; then
            export APPLE_SDK_PATH=/Applications/Xcode_12.5.1.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.3.sdk
          elif [ "${{ matrix.build.target_triple }}" = "aarch64-apple-ios" ]; then
            export APPLE_SDK_PATH=/Applications/Xcode_12.5.1.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS14.5.sdk
          elif [ "${{ matrix.build.target_triple }}" = "x86_64-apple-darwin" ]; then
            export APPLE_SDK_PATH=/Applications/Xcode_12.4.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.1.sdk
          elif [ "${{ matrix.build.target_triple }}" = "x86_64-apple-ios" ]; then
            export APPLE_SDK_PATH=/Applications/Xcode_12.4.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator14.4.sdk
          else
            echo "unhandled target triple: ${{ matrix.build.target_triple }}"
            exit 1
          fi

          ./build-macos.py --skip-toolchain --target-triple ${{ matrix.build.target_triple }} --python ${{ matrix.build.py }} --optimizations ${{ matrix.build.optimizations }}

      - name: Validate Distribution
        run: |
          chmod +x build/pythonbuild

          if [ "${{matrix.build.target_triple }}" = "x86_64-apple-darwin" ]; then
            EXTRA_ARGS="--run"
          fi

          build/pythonbuild validate-distribution ${EXTRA_ARGS} dist/*.tar.zst

      - name: Upload Distributions
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.build.py }}-${{ matrix.build.target_triple }}
          path: dist/*
